server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-roleplay-backend
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_roleplay?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: ai-roleplay-secret-key-2024
  expiration: 86400000 # 24小时

# AI服务配置
ai:
  zhipu:
    api-key: your-zhipu-api-key
    base-url: https://open.bigmodel.cn/api/paas/v4
    model: glm-4
  
  speech:
    baidu:
      app-id: your-baidu-app-id
      api-key: your-baidu-api-key
      secret-key: your-baidu-secret-key
    
    aliyun:
      access-key-id: your-aliyun-access-key-id
      access-key-secret: your-aliyun-access-key-secret
      app-key: your-aliyun-app-key

# 日志配置
logging:
  level:
    com.ai.roleplay: debug
    org.springframework.security: debug